functionality:
  name: example_r
  arguments:
    - name: --input
      type: file
      description: Path to the input file
      example: resources/datasets/Zhuang_2023_merfish_brain/dataset.h5ad
    - name: --output
      type: file
      description: Path to the output directory
      direction: output
      example: resources/results/example_python/prediction.h5ad
  resources:
    - type: R_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        packages:
          - anndata