name: build

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to deploy to. If not specified, `build-${BRANCH_NAME}` will be used.'
        required: false
      version:
        description: 'Version name to use for the build. If not specified, `build-${BRANCH_NAME}` will be used.'
        required: false

jobs:
  # phase 1
  list:
    runs-on: ubuntu-latest

    outputs:
      target_branch: ${{ steps.defaults.outputs.target_branch }}
      version: ${{ steps.defaults.outputs.version }}
      component_matrix: ${{ steps.set_matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: viash-io/viash-actions/setup@v5

    - name: Determine version tag from branch name
      id: defaults
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')

        VERSION=${{ github.event.inputs.version }}
        if [ -z "$VERSION" ]; then
          VERSION="build-$BRANCH_NAME"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

        TARGET_BRANCH=${{ github.event.inputs.target_branch }}
        if [ -z "$TARGET_BRANCH" ]; then
          TARGET_BRANCH="build-$BRANCH_NAME"
        fi
        echo "target_branch=$TARGET_BRANCH" >> $GITHUB_OUTPUT

    - name: Remove target folder from .gitignore
      run: |
        # allow publishing the target folder
        sed -i '/^target.*/d' .gitignore

    - uses: viash-io/viash-actions/ns-build@v5
      with:
        config_mod: .functionality.version := '${{ steps.defaults.outputs.version }}'
        parallel: true

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: ${{ steps.defaults.outputs.target_branch }}

    - id: ns_list
      uses: viash-io/viash-actions/ns-list@v5
      with:
        platform: docker
        src: src
        format: json

    - id: set_matrix
      run: |
        echo "matrix=$(jq -c '[ .[] | 
          { 
            "name": (.functionality.namespace + "/" + .functionality.name),
            "dir": .info.config | capture("^(?<dir>.*\/)").dir
          }
        ]' ${{ steps.ns_list.outputs.output_file }} )" >> $GITHUB_OUTPUT

  # phase 2
  build:
    needs: list

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list.outputs.component_matrix) }}

    steps:
    # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
    - uses: data-intuitive/reclaim-the-bytes@v2
    
    - uses: actions/checkout@v4

    - uses: viash-io/viash-actions/setup@v5

    - name: Build container
      uses: viash-io/viash-actions/ns-build@v5
      with:
        config_mod: .functionality.version := '${{ needs.list.outputs.version }}'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: build
        
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GTHB_USER }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Push container
      uses: viash-io/viash-actions/ns-build@v5
      with:
        config_mod: .functionality.version := '${{ needs.list.outputs.version }}'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: push