functionality:
  name: example_python
  arguments:
    - name: --input
      type: file
      description: Path to the input file
      example: resources/datasets/Zhuang_2023_merfish_brain/dataset.h5ad
    - name: --output
      type: file
      description: Path to the output directory
      example: resources/results/example_python/prediction.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: native
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - anndata
          - pandas
          # ... add more dependencies here ...
  - type: netflow