functionality:
  name: "sync_resources"
  namespace: "common"
  version: "build-main"
  arguments:
  - type: "string"
    name: "--input"
    alternatives:
    - "-i"
    description: "Path to the S3 bucket to sync from."
    info: null
    default:
    - "s3://openproblems-data/resources/spatial_ccc_experiments/"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Path to the test resource directory."
    info: null
    default:
    - "resources"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--quiet"
    description: "Displays the operations that would be performed using the specified\
      \ command without actually running them."
    info: null
    direction: "input"
    dest: "par"
  - type: "boolean_true"
    name: "--dryrun"
    description: "Does not display the operations performed from the specified command."
    info: null
    direction: "input"
    dest: "par"
  - type: "boolean_true"
    name: "--delete"
    description: "Files that exist in the destination but not in the source are deleted\
      \ during sync."
    info: null
    direction: "input"
    dest: "par"
  - type: "string"
    name: "--exclude"
    description: "Exclude all files or objects from the command that matches the specified\
      \ pattern."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Synchronise the test resources from s3 to resources_test"
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "amazon/aws-cli:2.7.12"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/sync_resources/config.vsh.yaml"
  platform: "native"
  output: "target/native/common/sync_resources"
  executable: "target/native/common/sync_resources/sync_resources"
  viash_version: "0.8.6"
  git_commit: "2fbc48a51cc34281a6f148cce4c280ee9b9495df"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
