functionality:
  name: cellxgene
  arguments:
    - name: --url
      type: string
      description: URL of the cellxgene dataset
      default: 'https://datasets.cellxgene.cziscience.com/2ae703d3-e98f-4db0-8477-43b75f7c543c.h5ad'
    - name: --output
      type: file
      description: Path to the output directory
      example: output.h5ad
      direction: output
      __merge__: ../../api/file_input.yaml
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: /common-resources/component_tests/run_and_check_output.py
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - anndata
          - pyyaml
          - scanpy
