functionality:
  name: "allen_brain_atlas_via_s3"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    info:
      summary: "The input data format."
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts."
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalised expression values."
          required: true
        obs:
        - type: "string"
          name: "celltype"
          description: "Cell type labels."
          required: true
        obsm:
        - type: "double"
          name: "spatial"
          description: "X and Y coordinates of cells/spots."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Reference of the dataset."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Description of the dataset."
          required: false
    example:
    - "output.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--brain_section_label"
    description: "A brain section label to subset the data with."
    info: null
    default:
    - "Zhuang-ABCA-1.080"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "saeyslab/spatial_ccc_experiments"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/saeyslab/spatial_ccc_experiments"
  setup:
  - type: "python"
    user: false
    packages:
    - "boto3"
    - "anndata"
    - "pandas"
    - "scanpy"
    - "pyyaml"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/dataset_loaders/allen_brain_atlas_via_s3/config.vsh.yaml"
  platform: "nextflow"
  output: "target/nextflow/allen_brain_atlas_via_s3"
  executable: "target/nextflow/allen_brain_atlas_via_s3/allen_brain_atlas_via_s3"
  viash_version: "0.8.6"
  git_commit: "b9bca6ee6099171bf1cc9783ce146c24be04a2d6"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
