functionality:
  name: allen_brain_atlas_via_pooch
  arguments:
    - name: --output
      type: file
      description: Path to the output directory
      example: output.h5ad
      direction: output
      __merge__: ../../api/file_input.yaml
    - name: --brain_section_label
      type: string
      description: Brain section label
      example: 'Zhuang-ABCA-1.080'
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: /common-resources/component_tests/run_and_check_output.py
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - pooch
          - anndata
          - pandas
          - scanpy
          - pyyaml
  - type: nextflow