functionality:
  name: "example_python"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--input"
    description: "Path to the input file"
    info: null
    example:
    - "resources/datasets/Zhuang_2023_merfish_brain/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    info: null
    example:
    - "resources/results/example_python/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "saeyslab/spatial_ccc_experiments"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/saeyslab/spatial_ccc_experiments"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata"
    - "pandas"
    upgrade: true
  entrypoint: []
  cmd: null
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/methods/example_python/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/example_python"
  executable: "target/docker/example_python/example_python"
  viash_version: "0.8.6"
  git_commit: "d9108a8d0902f4644b5972d75c1633c69755c41e"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
