functionality:
  name: "allen_brain_atlas_via_pooch"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    info: null
    example:
    - "output.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--brain_section_label"
    description: "Brain section label"
    info: null
    example:
    - "Zhuang-ABCA-1.080"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "saeyslab/spatial_ccc_experiments"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/saeyslab/spatial_ccc_experiments"
  setup:
  - type: "python"
    user: false
    packages:
    - "pooch"
    - "anndata"
    - "pandas"
    - "scanpy"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/dataset_loaders/allen_brain_atlas_via_pooch/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/allen_brain_atlas_via_pooch"
  executable: "target/docker/allen_brain_atlas_via_pooch/allen_brain_atlas_via_pooch"
  viash_version: "0.8.6"
  git_commit: "d9108a8d0902f4644b5972d75c1633c69755c41e"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
