functionality:
  name: example_r
  arguments:
    - name: --input
      type: file
      description: Path to the input file
      example: resources/datasets/Zhuang_2023_merfish_brain/dataset.h5ad
    - name: --output
      type: file
      description: Path to the output file
      direction: output
      example: resources/results/Zhuang_2023_merfish_brain/prediction.h5ad
    # TODO: Add more useful arguments
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran:
          - anndata
          - NMF
        github: 
          - jokergoo/circlize
          - jokergoo/ComplexHeatmap
          - jinworks/CellChat
