functionality:
  name: "cellxgene"
  version: "build-main"
  arguments:
  - type: "string"
    name: "--url"
    description: "URL of the cellxgene dataset"
    info: null
    example:
    - "https://datasets.cellxgene.cziscience.com/2ae703d3-e98f-4db0-8477-43b75f7c543c.h5ad"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    info: null
    example:
    - "output.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata"
    - "urlretrieve"
    upgrade: true
  entrypoint: []
  cmd: null
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/dataset_loaders/cellxgene/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/cellxgene"
  executable: "target/docker/cellxgene/cellxgene"
  viash_version: "0.8.6"
  git_commit: "2fbc48a51cc34281a6f148cce4c280ee9b9495df"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
