functionality:
  name: "cellxgene"
  version: "build-main"
  arguments:
  - type: "string"
    name: "--url"
    description: "URL of the cellxgene dataset"
    info: null
    default:
    - "https://datasets.cellxgene.cziscience.com/2ae703d3-e98f-4db0-8477-43b75f7c543c.h5ad"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    info:
      summary: "The input data format."
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts."
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalised expression values."
          required: true
        obs:
        - type: "string"
          name: "celltype"
          description: "Cell type labels."
          required: true
        obsm:
        - type: "double"
          name: "spatial"
          description: "X and Y coordinates of cells/spots."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Reference of the dataset."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Description of the dataset."
          required: false
    example:
    - "output.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "common-resources/component_tests/run_and_check_output.py"
    is_executable: true
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "saeyslab/spatial_ccc_experiments"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/saeyslab/spatial_ccc_experiments"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata"
    - "pyyaml"
    - "scanpy"
    upgrade: true
  entrypoint: []
  cmd: null
info:
  config: "/home/runner/work/spatial_ccc_experiments/spatial_ccc_experiments/src/dataset_loaders/cellxgene/config.vsh.yaml"
  platform: "docker"
  output: "target/docker/cellxgene"
  executable: "target/docker/cellxgene/cellxgene"
  viash_version: "0.8.6"
  git_commit: "d31d0883b51d4b8c73d8f16f4f3b2b4ad95fbbb9"
  git_remote: "https://github.com/saeyslab/spatial_ccc_experiments"
